export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const SAVE_POST_REQUEST = "SAVE_POST_REQUEST";
export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS";
export const SAVE_POST_FAILURE = "SAVE_POST_FAILURE";

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAILURE = "GET_ALL_POST_FAILURE";

export const GET_USER_POST_REQUEST = "GET_USER_POST_REQUEST";
export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS";
export const GET_USER_POST_FAILURE = "GET_USER_POST_FAILURE";

export const DELETE_USER_POST_REQUEST = "DELETE_USER_POST_REQUEST";
export const DELETE_USER_POST_SUCCESS = "DELETE_USER_POST_SUCCESS";
export const DELETE_USER_POST_FAILURE = "DELETE_USER_POST_FAILURE";

// Comment action types

export const CREATE_USER_COMMENT_REQUEST = "CREATE_USER_COMMENT_REQUEST";
export const CREATE_USER_COMMENT_SUCCESS = "CREATE_USER_COMMENT_SUCCESS";
export const CREATE_USER_COMMENT_FAILURE = "CREATE_USER_COMMENT_FAILURE";
