export const CREATE_USER_STORY_REQUEST = "CREATE_USER_STORY_REQUEST";
export const CREATE_USER_STORY_SUCCESS = "CREATE_USER_STORY_SUCCESS";
export const CREATE_USER_STORY_FAILURE = "CREATE_USER_STORY_FAILURE";

export const GET_USER_STORIES_REQUEST = "GET_USER_STORIES_REQUEST";
export const GET_USER_STORIES_SUCCESS = "GET_USER_STORIES_SUCCESS";
export const GET_USER_STORIES_FAILURE = "GET_USER_STORIES_FAILURE";
