export const CREATE_REEL_REQUEST = "CREATE_REEL_REQUEST";
export const CREATE_REEL_SUCCESS = "CREATE_REEL_SUCCESS";
export const CREATE_REEL_FAILURE = "CREATE_REEL_FAILURE";

export const UPDATE_REEL_REQUEST = "UPDATE_REEL_REQUEST";
export const UPDATE_REEL_SUCCESS = "UPDATE_REEL_SUCCESS";
export const UPDATE_REEL_FAILURE = "UPDATE_REEL_FAILURE";

export const GET_ALL_REELS_REQUEST = "GET_ALL_REELS_REQUEST";
export const GET_ALL_REELS_SUCCESS = "GET_ALL_REELS_SUCCESS";
export const GET_ALL_REELS_FAILURE = "GET_ALL_REELS_FAILURE";

export const GET_USER_REELS_REQUEST = "GET_USER_REELS_REQUEST";
export const GET_USER_REELS_SUCCESS = "GET_USER_REELS_SUCCESS";
export const GET_USER_REELS_FAILURE = "GET_USER_REELS_FAILURE";
