export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const RESET_USER = "RESET_USER";

export const GET_USER_PROFILE_ID_REQUEST = "GET_USER_PROFILE_ID_REQUEST";
export const GET_USER_PROFILE_ID_SUCCESS = "GET_USER_PROFILE_ID_SUCCESS";
export const GET_USER_PROFILE_ID_FAILURE = "GET_USER_PROFILE_ID_FAILURE";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAILURE = "USER_SEARCH_FAILURE";
